import { Ticket } from "./types";

export const mockTickets: Ticket[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    subject: "Cannot access dashboard",
    description: "Updated description with specific details about the issue.",
    created_at: "2024-10-25T21:42:23.802299",
    updated_at: "2024-10-25T21:52:30.108823",
    language: "en",
    status: "inProgress",
    category: "technical",
    sentiment: "neutral",
    strategy: "template",
    priority: "high",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    subject: "Billing issue",
    description: "Charged twice this month for the same service.",
    created_at: "2024-10-24T15:30:12.987654",
    updated_at: "2024-10-25T10:45:23.456789",
    language: "en",
    status: "open",
    category: "billing",
    sentiment: "negative",
    strategy: "autoAnswer",
    priority: "mid",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice@example.com",
    subject: "Feature request",
    description: "Requesting a new feature for better user experience.",
    created_at: "2024-10-23T09:10:45.123456",
    updated_at: "2024-10-23T10:00:00.000000",
    language: "en",
    status: "open",
    category: "support",
    sentiment: "positive",
    strategy: "template",
    priority: "low",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob@example.com",
    subject: "Password reset",
    description: "Having trouble resetting my password.",
    created_at: "2024-10-22T12:30:30.123456",
    updated_at: "2024-10-22T13:00:00.000000",
    language: "en",
    status: "closed",
    category: "technical",
    sentiment: "neutral",
    strategy: "autoAnswer",
    priority: "mid",
  },
  {
    id: 5,
    name: "Charlie Green",
    email: "charlie@example.com",
    subject: "Cancellation request",
    description: "Requesting cancellation of my subscription.",
    created_at: "2024-10-20T08:15:45.987654",
    updated_at: "2024-10-20T09:00:00.000000",
    language: "en",
    status: "inProgress",
    category: "billing",
    sentiment: "negative",
    strategy: "template",
    priority: "high",
  },
  {
    id: 6,
    name: "Diana Prince",
    email: "diana@example.com",
    subject: "Feedback on the product",
    description:
      "I really love using this product, but I have some suggestions.",
    created_at: "2024-10-19T14:45:30.123456",
    updated_at: "2024-10-19T15:00:00.000000",
    language: "en",
    status: "open",
    category: "support",
    sentiment: "positive",
    strategy: "autoAnswer",
    priority: "low",
  },
];
